# Generated by Django 5.0.2 on 2024-03-22 16:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
                ('address', models.TextField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('zipcode', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('amount', models.CharField(max_length=50)),
                ('payment_id', models.CharField(max_length=200, null=True)),
                ('paid', models.BooleanField(default=False, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='cart/Oreder_Img')),
                ('quantity', models.CharField(max_length=25)),
                ('price', models.CharField(max_length=50)),
                ('total', models.CharField(max_length=100)),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.order')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategories_name', models.CharField(max_length=50)),
                ('categories', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='eshop.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('desc', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='cart/image')),
                ('pub_date', models.DateField(default=django.utils.timezone.now)),
                ('categary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.categories')),
                ('subCategary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.subcategories')),
            ],
        ),
    ]
