# Generated by Django 5.0.2 on 2024-04-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_no',
            field=models.IntegerField(),
        ),
    ]
